# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.srcs/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'pdsa_system_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.gen/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pdsa_system_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.gen/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pdsa_system_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.srcs/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'pdsa_system_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.gen/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pdsa_system_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.gen/sources_1/bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pdsa_system_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
