# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/pdsa_updated_on_2_6/constraints/pdsa_kv260.xdc

# Block Designs: bd/pdsa_system/pdsa_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pdsa_system || ORIG_REF_NAME==pdsa_system} -quiet] -quiet

# IP: bd/pdsa_system/ip/pdsa_system_zynq_ultra_ps_e_0_0/pdsa_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pdsa_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pdsa_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/pdsa_system/ip/pdsa_system_axi_smc_0/pdsa_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pdsa_system_axi_smc_0 || ORIG_REF_NAME==pdsa_system_axi_smc_0} -quiet] -quiet

# IP: bd/pdsa_system/ip/pdsa_system_static_0_0/pdsa_system_static_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pdsa_system_static_0_0 || ORIG_REF_NAME==pdsa_system_static_0_0} -quiet] -quiet

# IP: bd/pdsa_system/ip/pdsa_system_rm_0_0/pdsa_system_rm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pdsa_system_rm_0_0 || ORIG_REF_NAME==pdsa_system_rm_0_0} -quiet] -quiet

# XDC: d:/pdsa_updated_on_2_6/build_scripts/project_bd_dfx_sep/pdsa_fpga_bd_dfx_sep.gen/sources_1/bd/pdsa_system/pdsa_system_ooc.xdc
